### PR TITLE
emplace any

### PR DESCRIPTION
**Pull request by beppemarazzi**
emplace ctor and modifier for meta::any (similar to std::any)
it eliminates extra moves in meta::type::construct

WARNING: it incorporates and relies on my previous PR #5

### CODE REVIEW

**Comment by skypjack** [comment]
I'm from mobile, I haven't looked into the code, so probably a dumb question: why does this eliminate extra moves in `meta::type::construct`?

**Comment by beppemarazzi** [comment]
In meta::internal::construct a new instance of T is created and then assigned to any, so a new any is move constructed from the just created instance of T and this triggers a move construction of a new T instance to be placed in any....

https://github.com/skypjack/meta/blob/da9051a53984cdea6ced4a18c59e43c5c5fd865e/src/meta/meta.hpp#L2098-L2110

I added some tests to count lifecycle operations (ctor, dtor, copyctor, movector, copy and move) on user's type and a global boolean `meta::internal::disable_construct_with_emplace_TODO_REMOVE_BEFORE_MERGE_EMPLACE` to test both behaviours

...waiting for your opinion...

**Comment by skypjack** [comment]
First of all, may I ask you to merge it with `master`? The other PR has been reviewed and this is out of sync right now.

That said, I don't think this does what you expect. I don't really understand why should we use `in_place_type_t` with `meta::any`. The purpose of this tag is literally to disambiguate when you want to construct `T` with an argument of type `U`, because `std::any` would construct internally a `U` otherwise. We can add an extra constructor to offer a similar functionality (that doesn't seem to be that useful when it comes to working with a runtime reflection system), but we cannot just replace the current constructor with this one because this changes completely the behavior of the class itself.  
Moreover, extra moves within `construct` were do to a bug (the you pointed out and fixed actually). They are already removed, in a sense. :-)

I'm not that sure this is correct to be honest. Let me know your thoughts on my reasoning.

**Comment by beppemarazzi** [comment]
Sorry for the delay... some family business.....
Rebased this on master.

About extra move: the key point is https://github.com/skypjack/meta/blob/5c8c4f62ef95ca1ab63cb72c755647f245a1b4dd/src/meta/meta.hpp#L2109
IMHO here we make the firs istance of `Type` **on the stack** and then we move construct an any that places the `Type` instance in it's internal storage **on the heap** (supposing no SBO). So the compiler must move the Type instance from stack to heap. With my proposal, the first `Type` instance is directly emplace-constructed inside the any storage, so it's not necessary to move it!
I wrote a couple of test to prove it

About the any emplace-constructor. It's not sobstituting another constructor, it's a new one. IMHO the usage of `in_place_type_t` is necessary to allow the compiler to deduce the `Type` we wanto to construct.
In my first implementation i directly wrote the `any::emplace`  modifier, but to make it exception safe i preferred to rely on emplace constructor and swap.

**Comment by skypjack** [comment]
You're right. The mobile up messed everything up, my fault.  
The implementation seems a bit redundant and I'd like to review and refine it.  
If it's fine for you, I'll merge it on a branch during the week, update it and then merge everything on `master` when done.

---

I don't get also why you replaced a `new` with an `std::unique_ptr` you `release` three lines below the creation.  
From my point of view, `new` was just fine there. What's your goal exactly?

**Comment by beppemarazzi** [comment]
> If it's fine for you, I'll merge ...

:+1:
-
> 
> I don't get also why you replaced a `new` with an `std::unique_ptr` you `release` three lines below the creation.
> From my point of view, `new` was just fine there. What's your goal exactly?

https://github.com/skypjack/meta/blob/5c8c4f62ef95ca1ab63cb72c755647f245a1b4dd/src/meta/meta.hpp#L374-L375

I want to provide basic exception safety. In case of a throwing copy-ctor or throwing move-ctor in the user's type (we are invoking it on line 375) i guess we are leaking `chunk`. Probably 99.9% of copy-ctors or move-ctors are `noexcept`, but imho with RAII we are more robust...

**Comment by skypjack** [comment]
Hi, sorry for the late. I'm merging it on `wip` as mentioned above. :+1:

**Comment by skypjack** [comment]
Please, take a look at branch `wip`.  
Also, it's failing on appveyor but I've not a Windows machine on which to reproduce the error. Could you help with that?  
Thanks.

**Comment by beppemarazzi** [comment]
> Could you help with that?

Sure! I guess the problem is a bug in MSVC compiler.
to fix the issue we have to replace:
https://github.com/skypjack/meta/blob/a715d8c26f2213873033f668c7b99cf51c356030/src/meta/meta.hpp#L393
with this:
```
constexpr bool useSBO = sizeof(actual_type) <= sizeof(void*);
if constexpr(useSBO) {
```

If you prefer i can make another PR with this....

**Comment by skypjack** [comment]
Uhu? Really?  
How is it that it works fine on `master`?  
I saw the comment in the PR but it thought it was related to an older version of VS, not the upstream.

---

Don't worry, I'll try it directly on `wip` later.  
Thanks for pointing it out. It's worth opening an issue to Microsoft btw.  
Did you succeed in reproducing it with a small example somehow?

**Comment by skypjack** [comment]
I'm shocked. VS picked the wrong path of the `if constexpr` despite the absolutely valid code. :man_facepalming:  
I'm wondering now why the version on `master` works, since it has exactly the same guard...

**Comment by beppemarazzi** [comment]
I have a little repro i've issued to MS....
My guess is this bug depends on 3 conditions (all mus be met)
1 - a function template with a type template argument followed by variadic args (i.e. our `template<typename Type, typename... Args>
    any(std::in_place_type_t<Type>, Args &&... args) {`)
2 - a type alias (i.e. our `using actual_type = std::remove_cv_t<std::remove_reference_t<Type>>;` but in my repro is enough to have `using actual_type = Type;`)
3 - a `if constexpr` directly using the aliased type (i.e. out `if constexpr(sizeof(actual_type) <= sizeof(void*))`)

breaking any of this three conditions, makes the compiler working correctly...

**Comment by skypjack** [comment]
Does `wip` look good now?

**Comment by beppemarazzi** [comment]
It's fine. All test passed...

**Comment by skypjack** [comment]
Anything else to point out? :-)  
I could cut a new minor version during the weekend otherwise.

**Comment by beppemarazzi** [comment]
Many thanks again for your great job!!!

**Comment by beppemarazzi** [comment]
Wait a minute....

i've just done another test with lifecycle_count_type, and now we have a lot of extra copy. I point to the changed implementation of `any::swap` during your last review...

**Comment by beppemarazzi** [comment]
@skypjack 
I would suggest an alternative implementation of `any.swap`.
This implementation doesn't suffer of extra copy in case we haven't sbo and also i beleive (uhm realy i hope...) it is not UB. Here i'm relying on the fact that in case of sbo inside storage we actualy have a `void*` that for sure is trivially copyable, so i guess it is not UB to copy storage in this case...
What do you think?

```
    friend void swap(any &lhs, any &rhs) {
        using std::swap;

        bool l_is_sbo = lhs && lhs.instance == &lhs.storage;
        bool r_is_sbo = rhs && rhs.instance == &rhs.storage;

        if(lhs && rhs) {
            storage_type buffer;
            void* tmp;
            if (l_is_sbo) {
                lhs.destroy_fn(lhs.storage);
                tmp = lhs.copy_fn(buffer, lhs.instance);
            }
            else {
                tmp = lhs.instance;
                buffer = lhs.storage;
            }
            if (r_is_sbo) {
                lhs.instance = rhs.copy_fn(lhs.storage, rhs.instance);
                rhs.destroy_fn(rhs.storage);
            }
            else {
                lhs.instance = rhs.instance;
                lhs.storage = rhs.storage;
            }
            if (l_is_sbo) {
                rhs.instance = lhs.copy_fn(rhs.storage, tmp);
                lhs.destroy_fn(buffer);
            }
            else {
                rhs.instance = tmp;
                rhs.storage = buffer;
            }
        } else if(lhs) {
            if (l_is_sbo) {
                rhs.instance = lhs.copy_fn(rhs.storage, lhs.instance);
                lhs.destroy_fn(lhs.storage);
                lhs.instance = nullptr;
            }
            else {
                rhs.instance = lhs.instance;
                rhs.storage = lhs.storage;
                lhs.instance = nullptr;
            }
        } else if(rhs) {
            if (r_is_sbo) {
                lhs.instance = rhs.copy_fn(lhs.storage, rhs.instance);
                rhs.destroy_fn(rhs.storage);
                rhs.instance = nullptr;
            }
            else {
                lhs.instance = rhs.instance;
                lhs.storage = rhs.storage;
                rhs.instance = nullptr;
            }
        }

        std::swap(lhs.node, rhs.node);
        std::swap(lhs.destroy_fn, rhs.destroy_fn);
        std::swap(lhs.compare_fn, rhs.compare_fn);
        std::swap(lhs.copy_fn, rhs.copy_fn);
    }
```

**Comment by skypjack** [comment]
Unfortunately it's not a matter of being trivially copyable or not.
The problem is that technically speaking there is no `void *` in the target storage (because you've never constructed such an object there). If you reinterpret cast the storage as if it was a `void *`, it's still an UB afaik.
It would be different if you constructed in place an empty `void *` and then you copied the byte in its storage area. This way, a reinterpret cast returns you a pointer to a **valid** object that has been explicitly constructed before to copy the content and therefore you can use it. In this case, it being trivially copyable gives you the guarantee that the object is still valid once you changed its byte representation.

**Comment by beppemarazzi** [comment]
What's about declaring something like
```
    union storage_type
    {
        std::aligned_storage_t<sizeof(void*), alignof(void*)> s;
        void* v;
    };
```
and use .s or .v in case of sbo or not
Do you think it is a viable approach?

**Comment by beppemarazzi** [comment]
Or, even better, what about this?
Here we are copying the type in case of sbo, and in-place constructing as `void*` in case of not sbo, without actually move or copy the real object...

```
    friend void swap(any &lhs, any &rhs) {
        using std::swap;

        bool l_is_sbo = lhs && lhs.instance == &lhs.storage;
        bool r_is_sbo = rhs && rhs.instance == &rhs.storage;

        if(lhs && rhs) {
            storage_type buffer;
            void* tmp;
            if (l_is_sbo) {
                tmp = lhs.copy_fn(buffer, lhs.instance);
                lhs.destroy_fn(lhs.storage);
            }
            else {
                tmp = lhs.instance;
            }
            if (r_is_sbo) {
                lhs.instance = rhs.copy_fn(lhs.storage, rhs.instance);
                rhs.destroy_fn(rhs.storage);
            }
            else {
                lhs.instance = rhs.instance;
                new (&lhs.storage) void*(rhs.instance);
            }
            if (l_is_sbo) {
                rhs.instance = lhs.copy_fn(rhs.storage, tmp);
                lhs.destroy_fn(buffer);
            }
            else {
                rhs.instance = tmp;
                new (&rhs.storage) void* (tmp);
            }
        } else if(lhs) {
            if (l_is_sbo) {
                rhs.instance = lhs.copy_fn(rhs.storage, lhs.instance);
                lhs.destroy_fn(lhs.storage);
                lhs.instance = nullptr;
            }
            else {
                rhs.instance = lhs.instance;
                new (&rhs.storage) void* (lhs.instance);
                lhs.instance = nullptr;
            }
        } else if(rhs) {
            if (r_is_sbo) {
                lhs.instance = rhs.copy_fn(lhs.storage, rhs.instance);
                rhs.destroy_fn(rhs.storage);
                rhs.instance = nullptr;
            }
            else {
                lhs.instance = rhs.instance;
                new (&lhs.storage) void* (rhs.instance);
                rhs.instance = nullptr;
            }
        }

        std::swap(lhs.node, rhs.node);
        std::swap(lhs.destroy_fn, rhs.destroy_fn);
        std::swap(lhs.compare_fn, rhs.compare_fn);
        std::swap(lhs.copy_fn, rhs.copy_fn);
    }
```

**Comment by skypjack** [comment]
Have you tried this with the current `master`? Does it work as expected?  
At a first glance we can refine the whole thing a bit to avoid some branches, but your idea sounds good.

**Comment by beppemarazzi** [comment]
Yes. All tests are ok.
And in case of no sbo the user's type is not copied nor moved with swap.

**Comment by skypjack** [comment]
Oh, so it's not the sbo case the one improved by your snippet, right? Sorry, I didn't realize it.  
Wouldn't it be enough to update the `copy_object` function then, so as to avoid the whole set of branches within `swap`?

**Comment by skypjack** [comment]
So, the whole idea here is to literally _steal_ the chunk of the other object when you've not sbo, right?
```
} else if(lhs) {
    if (l_is_sbo) {
        rhs.instance = lhs.copy_fn(rhs.storage, lhs.instance);
        lhs.destroy_fn(lhs.storage);
        lhs.instance = nullptr;
    } else {
        rhs.instance = lhs.instance;
        new (&rhs.storage) void* (lhs.instance);
        lhs.instance = nullptr;
    }
}
```

**Comment by beppemarazzi** [comment]
> Oh, so it's not the sbo case the one improved by your snippet, right?

Yes, the sbo case is not changed by my snippet.

> Wouldn't it be enough to update the `copy_object` function

mmmm don't know... what if we actually want to copy the object????
Probably we need a new `move_object` function and implement swap in term of that...
But IMHO we have to decide if implement swap in tem of move or vice-versa! 


> So, the whole idea here is to literally _steal_ the chunk of the other object when you've not sbo, right?

Right

**Comment by skypjack** [comment]
>But IMHO we have to decide if implement swap in tem of move

Well, it would make more sense actually. Shame on me for having implemented it in terms of copies before. :smile:  
Don't you think so?

**Comment by beppemarazzi** [comment]
At first view i thought it was not a big problem to copy in case of sbo... but i'm realizing that may exist an user type like an handle to a big data with value semantic. A such thing will go with sbo but using copy to implement swap (and then using swap to implement move like we are doing) is very bad because we are actually hiding the user defined move operator!!!
IMHO is definitely better to implement a couple of move functions like the copy pair (one for sbo and one for fat types) and then implement swap in terms of move with a more pretty linear code.
The drawback is that this will add another pointer to `move_fn` in the `any` footprint

**Comment by skypjack** [comment]
Well, swapping objects doesn't necessarily rely on the move operator (eg legacy code) but it's a nice to have, I agree.

>The drawback is that this will add another pointer to move_fn in the any footprint

Not a big problem. Instances of `any` are disposable objects, not something you should store aside in a large amount. My two cents.

I don't think writing the move functions is a great effort. I can do it next week (I'm alone at home with my son in the weekend, free time is off.  
If you want to try yourself in the meantime, you're welcome. :wink:

---

Side question: are you from Italy? If you're in Milan for the Italian C++ Conference next week, I'm there too and we can meet each other.

**Comment by skypjack** [comment]
In the meantime, I found 10 minutes to try it and I pushed everything on `wip`.  
I made a test and it's using `move_fn` internally. Can you test it as well and give me your feedback?
Thanks.

**Comment by beppemarazzi** [comment]
Found some problems with move: i had to separate `copy_fn_type`and `move_fn_type` because the move one has to have non const void* argument...
i.e.:
```
    using copy_fn_type = void* (*)(storage_type&, const void*);
    using move_fn_type = void *(*)(storage_type &, void *);

```

on my fork i pushed a wip branch beppemarazzi@7d5244f36259ef57bbde4f0c2cd75c37a58b4a2c with this fix and also the lifecycle_count test.
Counting lifecycle ops i also realized there was problems with the usage of swap in tests... we are calling `std::swap` so our `any::swap` gets called indirectly by any's move ctor... so if the user calls `std::swap` instead of 
```
    using std::swap;
    meta::any a{};
    meta::any b{};
    swap(a,b);
```
the move ctor of user's type is called more times.

Now i want to implement `move_object` with the "stealing chunk" so to not move at all in case of not sbo... 

---

> Side question: are you from Italy? If you're in Milan for the Italian C++ Conference next week, I'm there too and we can meet each other.

Provincia di Modena. Sono già iscritto per Milano... ci vediamo là!

**Comment by skypjack** [comment]
Shame on me. I'm alone at home with my son this weekend and I'm making the changes one line at a time when I find 5 minutes to do that. The results aren't that good, thanks for pointing it out! :smile: 

>Now i want to implement move_object with the "stealing chunk" so to not move at all in case of not sbo...

Sure, on `wip` there is only a draft to see if we agree on the basic approach. It's far from being complete.

---

>Provincia di Modena. Sono già iscritto per Milano... ci vediamo là!

Ottimo, io ho pure un talk, mi trovi sicuro!! :wink:

**Comment by skypjack** [comment]
>Now i want to implement move_object with the "stealing chunk" so to not move at all in case of not sbo...

The problem of a _stealing chunk_ approach is that you cannot guarantee the two types are the same, therefore you cannot just memcpy the memory of the two storage to swap the pointer because _theoretically_ it isn't allowed (ofc it works with all the compilers but the standard says that you aren't a good guy if you do that).

That said, you should intercept the following cases at least: sbo with sbo and same types, sbo with sbo and different types, sbo with no-sbo, no-sbo with no-sbo and same types, no-sbo with no-sbo and different types.
In all the cases where you've a no-sbo instance, you can _steal_ the pointer, no matter what the other `any` contains. However, you **must** know both the types and tells to the erased functions that do the dirty work that you want to steal instead of copying/moving.
At the end of the day, my concern is that this requires more support functions to work probably.

**Comment by beppemarazzi** [comment]
There is another subtle problem we are ignoring...
our implementation of swap (and by consequence of move assignment) is not `noexcept`.
Infact i'm convincing it is not possible to provide a noexcept swap implementation because of sbo.
My guess is that when we have sbo, we need to move construct (or move assign) directly the user type. So if the user type does not declare `noecxcept` his move operator, we also cannot declare noexcept.

I'm thinking a solution where the condition to go with sbo is not only based on size but also if the user type is `std::is_move_assignable` and/or `std::is_move_constructible`

Now i'm also understanding the flaw we had in the original swap implementation (the one before UB   skypjack/entt#180 ): it's not only a "theoretical" problem with UB, but is also possible to design a type that makes this implementation not working: is sufficent to put some logic in the data stored in type depending from this... i'm writing some tests with a such kind of type.

... this puzzle appears simple but is terribly complicated!!!!!

**Comment by beppemarazzi** [comment]
> The most interesting part here is that whenever we use `move_fn` we are actually in a situation where to steal the origin would be fine. Look at the code and tell me if my guess is wrong.

IMHO we can steal if and only if we are moving a no-sbo. In this case we can stay the actual user type instance fixed on it's place (on the heap) and implement our move/swap simply stealing the pointer as `void*`
In this case we can also alwais provide the `noexcept` guarantee.

But in case of sbo we MUST rely on the user defined "concept" ov move. This because the UB skypjack/entt#180 and (more pragmatically) because the user type may depend on the address of it's istance!!!!
And here we are `noexcept` only if the user defined move is `noexcept`.
This is why i'm thinking to go without sbo in this case, so we could declare `noexcept `on the `any` interface....

**Comment by skypjack** [comment]
In the meantime I've implemented a stealing version of any. Copies are drastically reduced. I'll refine and push it after dinner. :+1: :wink:

**Comment by beppemarazzi** [comment]
Nice!

**Comment by skypjack** [comment]
Upstream. **Please**, take a look at it. The whole thing is quite tricky and a bit of help is appreciated. :wink:

**Comment by beppemarazzi** [comment]
Whow!!! now we have also noexcept move and swap. 
It's exactly in the spirit i was thinking on.... But (believe me: i've a lot to learn from this code!!!) need some time to fully understand  `steal_object`...

**Comment by skypjack** [comment]
Indeed it's probably superfluous because the pointer is trivially destructible. That said, the goal is to properly destroy the instance of the pointer stored within storage. Note that I cannot invoke `destroy_fn` because it would destroy the heap-allocated object too.

**Comment by beppemarazzi** [comment]
> Uhm... Actually that line is useless as well as the line immediately after. We can leave there a pending pointer, it won't hurt in any case because of how swap and move work now.
> Am I wrong?

Agree about the second line `new (&from) chunk_type *{nullptr};` : there are no problems leaving that pointer.
About the `chunk->~chunk_type()` : understood the concept but i'm not so c++ deep-rules expert to say!

Anyway: done some test counting the actual moves/copies also in case of no noexcept move and all works as expected.
Also done a quick test with a "non relocatable" type to prove the danger of UB skypjack/entt#180. If you are interested look at my fork beppemarazzi/meta@7521154aa5b00adbc837f441b4a55bff795183bd

Just 2 minor points:
 

1. https://github.com/skypjack/meta/blob/34e458fd78014e383014178916db83484be61b80/src/meta/meta.hpp#L623
it's not better just `swap(*this, any);` ? IMHO `std::swap` does it's temp machinery and calls our `swap` only indirectly via move assignment

2. https://github.com/skypjack/meta/blob/34e458fd78014e383014178916db83484be61b80/src/meta/meta.hpp#L683-L687
isn't the swap pattern to simply call `swap` and let the ADL choose the right function? Alternatively remove https://github.com/skypjack/meta/blob/34e458fd78014e383014178916db83484be61b80/src/meta/meta.hpp#L668

**Comment by skypjack** [comment]
I think you're definitely right.  
May I ask you to open a PR directly against `wip`? Otherwise I'll update it in the evening, not a problem. I'm out the whole day unfortunately.

As a side note, it would be interesting now to compare `meta` with other solutions around.  
I've the feel that the last changes to `any` made it even more flexible and with better performance than what it offered before.

**Comment by beppemarazzi** [comment]
Seems all right for me!
Really: i didn't pratically nothing.... glad to partecipate with my little contribute to your unvaluable work!!!

See you saturday....

**Comment by skypjack** [comment]
Nah. I wouldn't have done it without your hints and help. You did **a lot**!! :wink: See you Saturday.

**Pull request merged**
